Elasticsearch: https://www.elastic.co/downloads/elasticsearch
Logstash: https://www.elastic.co/downloads/logstash
Kibana: https://www.elastic.co/downloads/kibana
Filebeat: https://www.elastic.co/downloads/beats/filebeat
OpenDistro for Elasticsearch: https://opendistro.github.io/for-elasticsearch/
Wazuh: https://wazuh.com/downloads/
